/* tslint:disable */
/* eslint-disable */
/**
 * Music Lab
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MusicErrorResponse
 */
export interface MusicErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof MusicErrorResponse
     */
    message: string;
}

/**
 * Check if a given object implements the MusicErrorResponse interface.
 */
export function instanceOfMusicErrorResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function MusicErrorResponseFromJSON(json: any): MusicErrorResponse {
    return MusicErrorResponseFromJSONTyped(json, false);
}

export function MusicErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MusicErrorResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function MusicErrorResponseToJSON(value?: MusicErrorResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

