/* tslint:disable */
/* eslint-disable */
/**
 * Music Lab
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MusicUnTagBody
 */
export interface MusicUnTagBody {
    /**
     * 
     * @type {string}
     * @memberof MusicUnTagBody
     */
    file: string;
    /**
     * 
     * @type {number}
     * @memberof MusicUnTagBody
     */
    tag: number;
}

/**
 * Check if a given object implements the MusicUnTagBody interface.
 */
export function instanceOfMusicUnTagBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "file" in value;
    isInstance = isInstance && "tag" in value;

    return isInstance;
}

export function MusicUnTagBodyFromJSON(json: any): MusicUnTagBody {
    return MusicUnTagBodyFromJSONTyped(json, false);
}

export function MusicUnTagBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): MusicUnTagBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'file': json['file'],
        'tag': json['tag'],
    };
}

export function MusicUnTagBodyToJSON(value?: MusicUnTagBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'file': value.file,
        'tag': value.tag,
    };
}

